### ISSUE TITLE
Highlight item listings if their float values are below a certain percentile

### ISSUE THREAD

**Issue by bmwalters** [Step7750/CSGOFloat-Extension#3]
> [this] might be useful since the API returns the min/max float for the skin and floats are distributed uniformly across their given wear range.

**Comment by Step7750** [comment]
I think this is where we'd want the user to have settings and a panel for it; allowing them to set the percentile/float that they want to highlight. Maybe having a sort of regex match for a given float? For instance, they could match that it starts with five 6's or something. That'd be pretty cool.

**Comment by Step7750** [comment]
If we go with a settings panel, should it be on the steamcommunity page itself w/ localStorage to save settings, or use Chrome's Extension setting system?

**Comment by bmwalters** [comment]
IMO we should use the WebExtensions/Chrome settings system, mainly for the benefit of syncing settings to the user's Google/Mozilla account

**Comment by Step7750** [comment]
Is it possible to use `chrome.storage.sync` and then we can just have an interactive settings pane injected into the page? We can bind the button/element events in the extension and save to `chrome.storage.sync`.

We have an added benefit of being able to use Valve's current dialog system/styling and modifying settings for a given item can be done on the page.

**Comment by bmwalters** [comment]
That is doable

**Comment by Step7750** [comment]
@bmwalters I've made the `feature/highlight` branch for this, feel free to add to it. I'm planning to work on this feature tomorrow or the day after. Again, thank you so much for the rewrite!

**Comment by Step7750** [comment]
I'm thinking that we could allow the ability to add highlight filters within the "Get all floats" div. We could separate the two sections with an `<hr>` tag styled like in the iteminfo div above it.

**Comment by Step7750** [comment]
For the filtering, I really want it to be powerful, but not have too much of a learning curve.

I think [Filtrex](https://github.com/joewalnes/filtrex) might be a good option here. We could even define a custom `regex` function or something along those lines that would try to match the string. Storing the expressions would also be stupidly simple and safe. Best of both worlds!

**Comment by Step7750** [comment]
@bmwalters I've worked on the `filtrex` branch quite a bit recently and was curious about your thoughts. The code is pretty messy at this point, but do you think the filtering system is easy to understand?

Basically, it highlights item divs with the specified user filter colour when it matches at least one filter. If it matches multiple filters, it will use the colour of the oldest filter (there is probably a better way to handle this). Filters are unique to a given item and saved to `sync` or `local`. I think the filter syntax with `filtrex` is really powerful and allows very complex filters.

If a filter fails to compile, it displays the compilation error below the input bar. I also modified `filtrex` to make sure it only allows some variable names and error out if not, with a friendly user message. There is also a little tutorial with the possible variable names. I plan to add a `percentile` variable and a `regex` function.

It seems that Firefox hasn't fully supported `storage.sync` yet, so it falls back onto `storage.local` when it isn't defined.

**Comment by bmwalters** [comment]
@Step7750 That's pretty cool so far. For the priority thing, maybe we could make the filter list reorderable and go by their order, or we could somehow display both colors on the item row.

I think the help dialog should open in a modal dialog (similar to the "Place Buy Order" popup).

It felt a bit odd to have the instant parse error feedback whenever I made a keystroke moving the elements; maybe the syntax checking could check only after some number of milliseconds since there hasn't been a keystroke or even only when you press the "add filter" button.

It is a very powerful system and I think users will find it helpful.

**Comment by Step7750** [comment]
@bmwalters I think it is helpful to have the help dialog inline with the input since you can use it as reference without having to open/close a modal. Making the list reorder-able would be the best way, doing this without adding dependencies would be pretty annoying.... 

It currently waits 250ms since there hasn't been a keystroke before trying to parse the expression. This was needed for obvious performance reasons, but I find it to be pretty useful to have immediate feedback. It definitely might be weird to a new user though.

Making existing filters editable is also a good idea, where would we show compilation error feedback for it though? Right below the filter?

Also, I thought it'd also be neat to have an option for a little beep sound or something when it finds a match for a specific filter.  We could use [AudioContext](https://developer.mozilla.org/en/docs/Web/API/AudioContext) and allow the user to change the frequency and other aspects of the beep! I think I might delay that for a bit though.

Thanks for the feedback!

**Comment by bmwalters** [comment]
@Step7750 Dependencies probably wouldn't be too much of an issue; we could use yarn for them and package them up before deployment.

I hadn't realized the filter parser already waits 250ms. You're right that it isn't much of a problem once you're used to it.

I suppose we could show the feedback below the filter and just make the row taller, or we could move the filter down to the edit area and change the button text to 'save changes' or something.

I don't think the noise is a good idea. Users already need to be paginating through the list and clicking the button, and the colored background is hard to miss. I don't see many users enabling the beep feature.

**Comment by Step7750** [comment]
@bmwalters I think just the feedback right below the filter would work fine. You're right about the audio, the highlight filters are hard to miss. It is possible that they have SIH enabled with 100 items per page, and just browse with another tab after clicking 'Get all floats', so it was mostly geared toward those types of power users.

In terms of the code, I'll probably make `filter` and `filters` classes since it is getting a bit ridiculous managing all those functions haha.  I probably won't work on the branch until tomorrow or Saturday, so feel free to add to it if you want! 👍

**Comment by Step7750** [comment]
Merged in #15
